# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created: Thu Mar 28 01:48:45 2024
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QCheckBox, QFileDialog
from PyQt5.QtGui import QIcon, QPixmap
import sys
import yaml

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1156, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videoDisplay = QtWidgets.QLabel(self.centralwidget)
        self.videoDisplay.setGeometry(QtCore.QRect(20, 20, 640, 480))
        self.videoDisplay.setObjectName("videoDisplay")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 10, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Loma")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 1151, 641))
        self.tabWidget.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.tabWidget.setObjectName("tabWidget")
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.startButton = QtWidgets.QPushButton(self.mainTab)
        self.startButton.setGeometry(QtCore.QRect(450, 570, 99, 27))
        self.startButton.setStyleSheet("QPushButton:hover{\n"
"background-color: green;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: white;\n"
"}")
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.mainTab)
        self.stopButton.setGeometry(QtCore.QRect(640, 570, 99, 27))
        self.stopButton.setStyleSheet("QPushButton:hover{\n"
"background-color: red;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: white;\n"
"}")
        self.stopButton.setObjectName("stopButton")
        self.graphicsView = QtWidgets.QGraphicsView(self.mainTab)
        self.scene = QtWidgets.QGraphicsScene()
        self.graphicsView.setScene(self.scene)
        self.graphicsView.setGeometry(QtCore.QRect(110, 60, 961, 451))
        self.graphicsView.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.mainTab, "")
        self.setTab = QtWidgets.QWidget()
        self.setTab.setObjectName("setTab")
        self.dataAcq = QtWidgets.QFrame(self.setTab)
        self.dataAcq.setGeometry(QtCore.QRect(10, 10, 531, 291))
        self.dataAcq.setStyleSheet("\n"
"background-color: rgb(240, 240, 240);")
        self.dataAcq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dataAcq.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataAcq.setObjectName("dataAcq")
        self.label_4 = QtWidgets.QLabel(self.dataAcq)
        self.label_4.setGeometry(QtCore.QRect(180, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.camButton = QtWidgets.QRadioButton(self.dataAcq)
        self.camButton.setGeometry(QtCore.QRect(200, 50, 81, 22))
        self.camButton.setObjectName("camButton")
        self.picButton = QtWidgets.QRadioButton(self.dataAcq)
        self.picButton.setGeometry(QtCore.QRect(40, 120, 81, 22))
        self.picButton.setObjectName("picButton")
        self.vidButton = QtWidgets.QRadioButton(self.dataAcq)
        self.vidButton.setGeometry(QtCore.QRect(40, 190, 81, 22))
        self.vidButton.setObjectName("vidButton")
        self.picEdit = QtWidgets.QLineEdit(self.dataAcq)
        self.picEdit.setGeometry(QtCore.QRect(130, 120, 261, 27))
        self.picEdit.setText("")
        self.picEdit.setObjectName("picEdit")
        self.vidEdit = QtWidgets.QLineEdit(self.dataAcq)
        self.vidEdit.setGeometry(QtCore.QRect(130, 190, 261, 27))
        self.vidEdit.setText("")
        self.vidEdit.setObjectName("vidEdit")
        self.picBrowse = QtWidgets.QPushButton(self.dataAcq)
        self.picBrowse.setGeometry(QtCore.QRect(420, 110, 41, 41))
        self.picBrowse.setStyleSheet("QPushButton:hover{\n"
"background-color: blue;\n"
"}")
        self.picBrowse.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Imágenes/browseIcone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picBrowse.setIcon(icon)
        self.picBrowse.setIconSize(QtCore.QSize(32, 32))
        self.picBrowse.setObjectName("picBrowse")
        self.picBrowse.clicked.connect(self.picFileDialog)
        self.vidBrowse = QtWidgets.QPushButton(self.dataAcq)
        self.vidBrowse.setGeometry(QtCore.QRect(420, 180, 41, 41))
        self.vidBrowse.setStyleSheet("QPushButton:hover{\n"
"background-color: blue;\n"
"}")
        self.vidBrowse.setText("")
        self.vidBrowse.setIcon(icon)
        self.vidBrowse.setIconSize(QtCore.QSize(32, 32))
        self.vidBrowse.setObjectName("vidBrowse")
        self.vidBrowse.clicked.connect(self.vidFileDialog)
        self.alertSet = QtWidgets.QFrame(self.setTab)
        self.alertSet.setGeometry(QtCore.QRect(590, 10, 531, 291))
        self.alertSet.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.alertSet.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.alertSet.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alertSet.setObjectName("alertSet")
        self.alertLabel = QtWidgets.QLabel(self.alertSet)
        self.alertLabel.setGeometry(QtCore.QRect(210, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.alertLabel.setFont(font)
        self.alertLabel.setObjectName("alertLabel")
        self.visualBox = QtWidgets.QCheckBox(self.alertSet)
        self.visualBox.setGeometry(QtCore.QRect(210, 61, 171, 61))
        self.visualBox.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Imágenes/visionON.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("Imágenes/visionON.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("Imágenes/visionON.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("Imágenes/visionON.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("Imágenes/visionOFF.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.visualBox.setIcon(icon1)
        self.visualBox.setIconSize(QtCore.QSize(64, 64))
        self.visualBox.setChecked(False)
        self.visualBox.setTristate(False)
        self.visualBox.stateChanged.connect(self.toggleVisionIcon)
        self.visualBox.setObjectName("visualBox")
        self.soundBox = QtWidgets.QCheckBox(self.alertSet)
        self.soundBox.setGeometry(QtCore.QRect(210, 180, 111, 81))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Imágenes/soundOFF.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.soundBox.setIcon(icon2)
        self.soundBox.setIconSize(QtCore.QSize(64, 64))
        self.soundBox.stateChanged.connect(self.toggleSoundIcon)
        self.soundBox.setObjectName("soundBox")
        self.senSet = QtWidgets.QFrame(self.setTab)
        self.senSet.setGeometry(QtCore.QRect(10, 310, 531, 241))
        self.senSet.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.senSet.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.senSet.setFrameShadow(QtWidgets.QFrame.Raised)
        self.senSet.setObjectName("senSet")
        self.senSetLabel = QtWidgets.QLabel(self.senSet)
        self.senSetLabel.setGeometry(QtCore.QRect(180, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.senSetLabel.setFont(font)
        self.senSetLabel.setObjectName("senSetLabel")
        self.visualSenList = QtWidgets.QComboBox(self.senSet)
        self.visualSenList.setGeometry(QtCore.QRect(330, 60, 51, 27))
        self.visualSenList.setStyleSheet("QPushButton:hover{\n"
"background-color: blue;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: white;\n"
"}")
        self.visualSenList.setObjectName("visualSenList")
        self.visualSenList.addItem("")
        self.visualSenList.addItem("")
        self.visualSenList.addItem("")
        self.visualSenLabel = QtWidgets.QLabel(self.senSet)
        self.visualSenLabel.setGeometry(QtCore.QRect(110, 70, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.visualSenLabel.setFont(font)
        self.visualSenLabel.setObjectName("visualSenLabel")
        self.soundSenList = QtWidgets.QComboBox(self.senSet)
        self.soundSenList.setGeometry(QtCore.QRect(330, 90, 51, 27))
        self.soundSenList.setStyleSheet("QPushButton:hover{\n"
"background-color: blue;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: white;\n"
"}")
        self.soundSenList.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.soundSenList.setObjectName("soundSenList")
        self.soundSenList.addItem("")
        self.soundSenList.addItem("")
        self.soundSenList.addItem("")
        self.soundSenLabel = QtWidgets.QLabel(self.senSet)
        self.soundSenLabel.setGeometry(QtCore.QRect(110, 100, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.soundSenLabel.setFont(font)
        self.soundSenLabel.setObjectName("soundSenLabel")
        self.label_8 = QtWidgets.QLabel(self.senSet)
        self.label_8.setGeometry(QtCore.QRect(180, 140, 110, 90))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("Imágenes/screb.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.camCalSet = QtWidgets.QFrame(self.setTab)
        self.camCalSet.setGeometry(QtCore.QRect(590, 310, 531, 241))
        self.camCalSet.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.camCalSet.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.camCalSet.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camCalSet.setObjectName("camCalSet")
        self.camCalLabel = QtWidgets.QLabel(self.camCalSet)
        self.camCalLabel.setGeometry(QtCore.QRect(200, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.camCalLabel.setFont(font)
        self.camCalLabel.setObjectName("camCalLabel")
        self.focalLabel = QtWidgets.QLabel(self.camCalSet)
        self.focalLabel.setGeometry(QtCore.QRect(70, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.focalLabel.setFont(font)
        self.focalLabel.setObjectName("focalLabel")
        self.focalEdit = QtWidgets.QLineEdit(self.camCalSet)
        self.focalEdit.setGeometry(QtCore.QRect(180, 80, 101, 27))
        self.focalEdit.setText("")
        self.focalEdit.setObjectName("focalEdit")
        self.icpEdit = QtWidgets.QLineEdit(self.camCalSet)
        self.icpEdit.setGeometry(QtCore.QRect(190, 140, 101, 27))
        self.icpEdit.setText("")
        self.icpEdit.setObjectName("icpEdit")
        self.icpLabel = QtWidgets.QLabel(self.camCalSet)
        self.icpLabel.setGeometry(QtCore.QRect(30, 140, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.icpLabel.setFont(font)
        self.icpLabel.setObjectName("icpLabel")
        self.epsLine = QtWidgets.QLineEdit(self.camCalSet)
        self.epsLine.setGeometry(QtCore.QRect(180, 200, 111, 27))
        self.epsLine.setText("")
        self.epsLine.setObjectName("epsLine")
        self.epsLabel = QtWidgets.QLabel(self.camCalSet)
        self.epsLabel.setGeometry(QtCore.QRect(30, 200, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.epsLabel.setFont(font)
        self.epsLabel.setObjectName("epsLabel")
        self.radialLabel = QtWidgets.QLabel(self.camCalSet)
        self.radialLabel.setGeometry(QtCore.QRect(360, 50, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.radialLabel.setFont(font)
        self.radialLabel.setObjectName("radialLabel")
        self.k1Edit = QtWidgets.QLineEdit(self.camCalSet)
        self.k1Edit.setGeometry(QtCore.QRect(380, 80, 71, 27))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.k1Edit.setFont(font)
        self.k1Edit.setText("")
        self.k1Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.k1Edit.setObjectName("k1Edit")
        self.k2Edit = QtWidgets.QLineEdit(self.camCalSet)
        self.k2Edit.setGeometry(QtCore.QRect(380, 110, 71, 27))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.k2Edit.setFont(font)
        self.k2Edit.setText("")
        self.k2Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.k2Edit.setObjectName("k2Edit")
        self.k3Edit = QtWidgets.QLineEdit(self.camCalSet)
        self.k3Edit.setGeometry(QtCore.QRect(380, 140, 71, 27))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.k3Edit.setFont(font)
        self.k3Edit.setText("")
        self.k3Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.k3Edit.setObjectName("k3Edit")
        self.k4Edit = QtWidgets.QLineEdit(self.camCalSet)
        self.k4Edit.setGeometry(QtCore.QRect(380, 170, 71, 27))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.k4Edit.setFont(font)
        self.k4Edit.setText("")
        self.k4Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.k4Edit.setObjectName("k4Edit")
        self.k5Edit = QtWidgets.QLineEdit(self.camCalSet)
        self.k5Edit.setGeometry(QtCore.QRect(380, 200, 71, 27))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.k5Edit.setFont(font)
        self.k5Edit.setText("")
        self.k5Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.k5Edit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.k5Edit.setObjectName("k5Edit")
        self.applyButton = QtWidgets.QPushButton(self.setTab)
        self.applyButton.setGeometry(QtCore.QRect(440, 560, 99, 27))
        self.applyButton.setStyleSheet("QPushButton:hover{\n"
"background-color: green;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: white;\n"
"}")
        self.applyButton.setObjectName("applyButton")
        self.applyButton.clicked.connect(self.applyConfig)
        self.cancelButton = QtWidgets.QPushButton(self.setTab)
        self.cancelButton.setGeometry(QtCore.QRect(590, 560, 99, 27))
        self.cancelButton.setStyleSheet("QPushButton:hover{\n"
"background-color: red;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: white;\n"
"}")
        self.cancelButton.setObjectName("cancelButton")
        self.tabWidget.addTab(self.setTab, "")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 700, 291, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(850, 700, 121, 17))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(990, 10, 41, 61))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Imágenes/Univalle.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1056, 20, 81, 41))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Imágenes/psi.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(336, 10, 61, 61))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Imágenes/logo.svg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "UV - LDWS"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainTab), _translate("MainWindow", "Processing"))
        self.label_4.setText(_translate("MainWindow", "Data acquisition"))
        self.camButton.setText(_translate("MainWindow", "Camera"))
        self.picButton.setText(_translate("MainWindow", "Picture"))
        self.vidButton.setText(_translate("MainWindow", "Video"))
        self.picEdit.setPlaceholderText(_translate("MainWindow", "Path..."))
        self.vidEdit.setPlaceholderText(_translate("MainWindow", "Path..."))
        self.alertLabel.setText(_translate("MainWindow", "Alert settings"))
        self.senSetLabel.setText(_translate("MainWindow", "Sensibility settings"))
        self.visualSenList.setItemText(0, _translate("MainWindow", "1"))
        self.visualSenList.setItemText(1, _translate("MainWindow", "2"))
        self.visualSenList.setItemText(2, _translate("MainWindow", "3"))
        self.visualSenLabel.setText(_translate("MainWindow", "Visual alert sensibility:"))
        self.soundSenList.setItemText(0, _translate("MainWindow", "1"))
        self.soundSenList.setItemText(1, _translate("MainWindow", "2"))
        self.soundSenList.setItemText(2, _translate("MainWindow", "3"))
        self.soundSenLabel.setText(_translate("MainWindow", "Sound alert sensibility:"))
        self.camCalLabel.setText(_translate("MainWindow", "Camera calibration"))
        self.focalLabel.setText(_translate("MainWindow", "Focal length:"))
        self.focalEdit.setPlaceholderText(_translate("MainWindow", "in mm"))
        self.icpEdit.setPlaceholderText(_translate("MainWindow", "x, y pixels"))
        self.icpLabel.setText(_translate("MainWindow", "Image center point:"))
        self.epsLine.setPlaceholderText(_translate("MainWindow", "in megapixels"))
        self.epsLabel.setText(_translate("MainWindow", "Efective pixel size:"))
        self.radialLabel.setText(_translate("MainWindow", "Radial distortion:"))
        self.k1Edit.setPlaceholderText(_translate("MainWindow", "k1"))
        self.k2Edit.setPlaceholderText(_translate("MainWindow", "k2"))
        self.k3Edit.setPlaceholderText(_translate("MainWindow", "k3"))
        self.k4Edit.setPlaceholderText(_translate("MainWindow", "k4"))
        self.k5Edit.setPlaceholderText(_translate("MainWindow", "k5"))
        self.applyButton.setText(_translate("MainWindow", "Apply"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setTab), _translate("MainWindow", "Settings"))
        self.label_2.setText(_translate("MainWindow", "Developed by: Juan Martin Davila Herrera"))
        self.label_3.setText(_translate("MainWindow", "Code: 201842208"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

